- name: Configure development
  hosts: all
  become: True
  vars:
    user: ubuntu
    key_file: /etc/nginx/ssl/nginx.key
    cert_file: /etc/nginx/ssl/nginx.crt
    conf_file: /etc/nginx/sites-available/default
    server_name: localhost
  tasks:
      - name: set timezone to Asia/Tokyo
        file: src=/usr/share/zoneinfo/Asia/Tokyo dest=/etc/localtime state=link force=yes

      - name: install with_items
        apt:
            name: "{{ item.name }}"
            state: installed
        register: Result
        with_items:
            - name: zsh
            - name: tmux
            - name: vim-gnome
            - name: git
            - name: openjdk-8-jdk

      - name: results
        debug: var=Result.results

      - name: set zsh as default shell for vagrant user
        command: chsh -s '/bin/zsh' ubuntu

      - setup:
        become: False
        become_user: "{{ user }}"

      - name: git clone .dotfiles pyenv
        become: False
        become_user: "{{ user }}"
        git:
            repo: "{{ item.repo }}"
            dest: "{{ item.dest }}"
        register: Result
        with_items:
            - repo: https://github.com/SeijiZ/.dotfiles
              dest: "{{ ansible_env.HOME }}/.dotfiles"
            - repo: https://github.com/pyenv/pyenv
              dest: "{{ ansible_env.HOME }}/.pyenv"

      - name: results
        debug: var=Result.results

